blueprints/base.py
from flask import *

bp = Blueprint("base", __name__, url_prefix="/base")
@bp.route("/")
def base():
    return render_template("base.html")

@bp.route("/r")
def base_r():
    return render_template("base_rightbar.html")

@bp.route("/l")
def base_l():
    return render_template("base_leftbar.html")

blueprints/create_post.py
from flask import *
import db
import utils
# from utils import sanitizer

bp = Blueprint("create_post", __name__, url_prefix="/post")
@bp.route("/create", methods=["POST", "GET"])
def create_post():
    if request.method == 'POST':
        return add_post()
    elif session.get("user") != None:
        categories = db.get_category_titles()
        data = {
            "categories": categories
        }
        return render_template("create_post.html", data=data)
    else:
        return redirect("/login")

def add_post():
    if session.get("user") != None:
        data = request.form
        # print(request.form)
        title = data.get("title")
        content = data.get("content")
        # Sanitize the content
        content = utils.sanitizer.sanitize(content)
        category = data.get("category")
        user_id = session["user"]["userinfo"]["sub"]
        db.add_post(title, content, category, user_id, "POST")
    return redirect("/")

@bp.route("/detail/<post_id>", methods=["POST", "GET"])
def detail(post_id):
    post = db.get_post_by_id(post_id)
    post_data = {
        "post_title": post[7],
        "post_content": post[2],
        "post_category":post[3].lower(),
        "post_time":post[4].strftime("%m/%d/%Y, %H:%M:%S"),
        "post_id":post_id,
    }

    category = db.get_category_by_name(post[3])
    category_data={
        "category_description": category[1],
        "category_icon" : category[2]
    }

    author_id = post[1]
    author = db.get_user_by_id(author_id)[0]
    author_post = db.get_post_count_by_user(author_id)
    author_data = {
            "author_img": author[2],
            "author_bio": author[3],
            "author_name": author[1],
            "author_fan": 3,##add ollowers if we decide we want to do it
            "author_post":author_post[0],
        }
    
    comments = db.get_comments_by_post_id(post_id)
    if comments:
        for comment in comments:
            comment_user= db.get_user_by_id(comment[1])[0]
            comment[1]=comment_user
            comment[4] = utils.get_elapsed_time(comment[4])

    if session.get("user") != None:
        if request.method == "POST":
            return create_comment(post_id)
        else:
            user = session["user"]["userinfo"]["nickname"]
            return render_template('details.html', comments=comments,post_data=post_data, author_data=author_data, user=user, category_data=category_data)
    else:   
        return render_template('details.html', comments=comments,post_data=post_data, author_data=author_data, category_data=category_data)


def create_comment(post_id):
    content = request.form.get("content")
    print(content)
    content = utils.sanitizer.sanitize(content)
    user_id = session["user"]["userinfo"]["sub"]
    db.add_comment(user_id, post_id, content)
    return redirect(f"/post/detail/{post_id}")

blueprints/home.py
from flask import *
import db
import utils
from functools import wraps

bp = Blueprint("home", __name__, url_prefix="/")
@bp.route("/")
@bp.route("/home")
def home():
    page = request.args.get('page')
    if page == None:
        page = 0
    else:
        page = int(page)
    recent_posts = db.get_recent_posts(page=page)

    # print(recent_posts[0][1])
    # print(recent_posts[2][8])

    for post in recent_posts:
        post[3] = utils.get_elapsed_time(post[3]) # convert timestamp to elapsed time

        # parser = utils.MyHTMLParser()
        # parser.feed(post[1])
        # raw_text = parser.rawText

        # db.set_raw_text(post[8], raw_text)
    
    page_count = utils.get_total_pages(db.get_post_count()[0])

    trending_tags = db.get_trending_sub_categories()

    data = {
        "recent_posts": recent_posts,
        "page_count": page_count,
        "page": page,
        "trending_tags": trending_tags,
        "post_url": request.url_root + "categories/"
    }
    return render_template("home.html", data=data)

# https://flask.palletsprojects.com/en/2.2.x/patterns/viewdecorators/
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get('user') is None:
            return redirect(url_for('login', next=request.url_root))
        return f(*args, **kwargs)
    return decorated_function

### API for getting likes
@bp.route("/post/<int:post_id>/like",methods=["GET"])
def get_post_likes(post_id):
    if (session.get("user")):
        return jsonify({'likes': db.get_likes(post_id), 'you_like': db.get_does_like(post_id, session["user"]["userinfo"]["sub"])})
    else:
        return jsonify({'likes': db.get_likes(post_id),'you_like':False})
        

@bp.route("/post/<int:post_id>/like1",methods=["POST"])
@login_required
def like_post(post_id):
    db.like_post(post_id, session["user"]["userinfo"]["sub"])
    return jsonify({'likes': db.get_likes(post_id), 'you_like': True})

@bp.route("/post/<int:post_id>/like1",methods=["DELETE"])
@login_required
def unlike_pen(post_id):
    db.unlike_post(post_id, session["user"]["userinfo"]["sub"])
    return jsonify({'likes': db.get_likes(post_id), 'you_like': False})

blueprints/login.py
# from flask import *

# bp = Blueprint("login", __name__, url_prefix="/login")
# @bp.route("/")
# def login():
#     return render_template("login.html")

blueprints/profile.py
# from werkzeug.utils import secure_filename
from flask import *
import db, boto3,random
import utils
from os import environ as env
# from utils import sanitizer

s3 = boto3.client('s3',
                  aws_access_key_id=env['AWS_ACCESS_KEY_ID'],
                  aws_secret_access_key=env['AWS_SECRET_ACCESS_KEY'])

bp = Blueprint("profile", __name__, url_prefix="/profile")

@bp.route("/", methods=["GET", "POST"])
def profile():
    if session.get("user"):
        if request.method == "POST":
            return update()
        user_id = session["user"]["userinfo"]["sub"]
        user = db.get_user_by_id(user_id)
        user_img = user[0]['photo_url']
        user_bio = user[0]['bio']
        user_name = session["user"]["userinfo"]["nickname"]
        user_post = 2
        user_fan = 3

        page = request.args.get('page')
        if page == None:
            page = 0
        else:
            page = int(page)

        recent_posts = db.get_recent_posts_by_user(user_name, type="POST", page=page)
        for post in recent_posts:
            post[3] = utils.get_elapsed_time(post[3]) # convert timestamp to elapsed time

        recent_discussions = db.get_recent_discussion_by_user_id(user_id,type="DISCUSSION")
        for discussion in recent_discussions:
            discussion[3] = utils.get_elapsed_time(discussion[3]) # convert timestamp to elapsed time

        page_count = utils.get_total_pages(db.get_post_count(type="DISCUSSION")[0])

        data = {
            "user_img": user_img,
            "user_bio": user_bio,
            "user_name": user_name,
            "user_post": user_post,
            "user_fan": user_fan,
            "recent_posts": recent_posts,
            "recent_discussions": recent_discussions,
            "page_count": page_count,
            "page": page
        }
        return render_template("profile.html", data=data,post_url=request.url_root + "categories/")
    else:
        return redirect("/")

def update():
    content = request.form.get("content")
    user_id = session["user"]["userinfo"]["sub"]
    bio = utils.sanitizer.sanitize(content)
    db.update_user_bio(user_id, bio)
    return redirect("/profile")
 


@bp.route('/upload', methods=['POST'])
def upload():
  file = request.files['photo']
  user_id = session["user"]["userinfo"]["sub"]
  filename = f"{user_id}/profile_photo"
  s3.upload_fileobj(file, BUCKETNAME, filename)
  photo_url = PHOTO_URL
  db.update_user_img(photo_url,user_id)
  return '', 204

blueprints/search.py
from flask import *
import db, utils

bp = Blueprint("search", __name__, url_prefix="/search")
@bp.route("/", methods=["GET"])
def get_search():
    return render_template("search.html", data=None)

@bp.route("/results", methods=["GET"])
def search_results():
    page = int(request.args.get('page', '0'))
    # page = int(page)
    query = request.args.get('search_query', '')
    post_type = request.args.get('post_type', '')
    if post_type:
        search_results = db.search_post_type_full_text_content(query, post_type, page=page)
    else:
        search_results = db.search_full_text_content(query, page=page)
    data = []
    for result in search_results:
        cur_entry = {
            "id": result[0],
            "user_id": result[1],
            "content": result[2],
            "category": result[3],
            "post_date": utils.get_elapsed_time(result[4]),
            "post_type": result[5],
            "likes": result[6],
            "title": result[7],
            "raw_text": result[8]
        }

        data.append(cur_entry)

    page_count = utils.get_total_pages(db.get_full_text_search_count(query)[0])

    data = {
        "search_results": data,
        "page_count": page_count,
        "page": page,
        "query": query,
        "post_url": request.url_root + "categories/",
        "post_type": post_type
    }
    return render_template("search.html", data=data)

@bp.route("/", methods=["POST"])
def search():
    page = request.args.get('page')
    if not page:
        page = 0
    else:
        page = int(page)
    form = request.form
    category = form['search_query']
    category = category.lower()
    search_results = db.search_by_category(category, page=page)

    for search in search_results:
        # print(search[4])
        search[3] = utils.get_elapsed_time(search[3])

    page_count = utils.get_total_pages(db.get_search_count_by_category(category)[0])

    print(db.get_search_count_by_category(category)[0])
    data = {
        "search_results": search_results,
        "page_count": page_count,
        "page": page
    }
    return render_template("search.html", data=data)

templates/base_leftbar.html
{% extends "base.html" %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1-4">
      <div class="separator"></div>
      <div id="content-left">
        {% block left_content %}
        <h2>Sample Sidebar</h2>
        {% endblock %}
      </div>
    </div>
    <div class="pure-u-3-4">
      <div class="separator"></div>
      <div class="content-right-large">
        {% block main_content %}
          <h2>Sample Heading</h2>
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

templates/base_multibar.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g">
    <div class="pure-u-1-4">
      <div class="separator"></div>
      <div id="content-left">
        {% block left_content %}
        <h2>Sample Sidebar</h2>
        {% endblock %}
      </div>
    </div>
    <div class="pure-u-1-2">
      <div class="separator"></div>
      <div id="content">
      {% block main_content %}
      <h2>Sample Heading</h2>
      {% endblock %}
    </div>
    </div>
    <div class="pure-u-1-4">
      <div class="separator"></div>
      <div id="content-right">
        {% block right_content %}
        <h2>Sample Sidebar</h2>
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

templates/base_rightbar.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g">
    <div class="pure-u-3-4">
      <div class="separator"></div>
      <div id="content-left-large">
      {% block main_content %}
      <h2>Sample Heading</h2>
      {% endblock %}
    </div>
    </div>
    <div class="pure-u-1-4">
      <div class="separator"></div>
      <div id="content-right">
        {% block right_content %}
        <h2>Sample Sidebar</h2>
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

templates/community_feed.html
{% extends "base.html" %}

{% block css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/community_feed.css') }}">
{% endblock %}
{% block js_scripts %}
    <script async defer src="{{ url_for('static', filename='js/community_feed.js') }}"></script>
{% endblock %}

{% block content %}
<div class="pure-g">
    <div class="pure-u-1-4">
        <div class="separator"></div>
        <div id="content-left-large">
            <div id="filter-feed">
                <form id="filterForm" class="pure-form pure-form-stacked">
                    <fieldset>
                        <div id="advancedFilter">Filter Feed</div>
                            <div id="filterOptions">
                                <div id="categoryOptions">
                                    <span class="pure-form-message">Category:</span>
                                    <label for="categories1" class="pure-checkbox">
                                        <input type="checkbox" id="categories1" name="categories1">Sample1
                                    </label>
                                    <label for="categories2" class="pure-checkbox">
                                        <input type="checkbox" id="categories2" name="categories2">Sample2
                                    </label>
                                    <label for="categories3" class="pure-checkbox">
                                        <input type="checkbox" id="categories3" name="categories3">Sample3
                                    </label>
                                    <label for="categories4" class="pure-checkbox">
                                        <input type="checkbox" id="categories4" name="categories4">Sample4
                                    </label>     
                                </div>
                                <div id="subcategoryOptions">
                                    <span class="pure-form-message">Sub-Category:</span>
                                    <label for="sub-categories1" class="pure-checkbox">
                                        <input type="checkbox" id="sub-categories1" name="sub-categories1">Sample1
                                    </label>
                                    <label for="sub-categories2" class="pure-checkbox">
                                        <input type="checkbox" id="sub-categories2" name="sub-categories2">Sample2
                                    </label>
                                    <label for="sub-categories3" class="pure-checkbox">
                                        <input type="checkbox" id="sub-categories3" name="sub-categories3">Sample3
                                    </label>
                                    <label for="sub-categories4" class="pure-checkbox">
                                        <input type="checkbox" id="sub-categories4" name="sub-categories4">Sample4
                                    </label>     
                                </div>
                                <div id="characterOptions">
                                    <span class="pure-form-message">Characters:</span>
                                    <label for="characters1" class="pure-checkbox">
                                        <input type="checkbox" id="characters1" name="characters1">Sample1
                                    </label>
                                    <label for="characters2" class="pure-checkbox">
                                        <input type="checkbox" id="characters2" name="characters2">Sample2
                                    </label>
                                    <label for="character3" class="pure-checkbox">
                                        <input type="checkbox" id="character3" name="character3">Sample3
                                    </label>
                                    <label for="character4" class="pure-checkbox">
                                        <input type="checkbox" id="character4" name="character4">Sample4
                                    </label>     
                                </div>
                                <div id="gameOptions">
                                    <span class="pure-form-message">Games:</span>
                                    <label for="game1" class="pure-checkbox">
                                        <input type="checkbox" id="game1" name="game1">Sample1
                                    </label>
                                    <label for="game2" class="pure-checkbox">
                                        <input type="checkbox" id="game2" name="game2">Sample2
                                    </label>
                                    <label for="game3" class="pure-checkbox">
                                        <input type="checkbox" id="game3" name="game3">Sample3
                                    </label>
                                    <label for="game4" class="pure-checkbox">
                                        <input type="checkbox" id="game4" name="game4">Sample4
                                    </label>     
                                </div>
                                <button class="pure-button pure-button-primary">Apply Filters</button>
                            </div>
                    </fieldset>
                </form>
            </div>
            <div id="followers-toggle">
                <p>Followers Only</p>
                <label class="switch">
                    <input type="checkbox">
                    <span class="slider round"></span>
                  </label>
            </div>
        </div>
    </div>
    <div class="pure-u-1-2">
        <div class="separator"></div>
        {% if session.get("user") %}
            <div id="content-left-large">
                <div class="pure-g">
                    <div class="pure-u-1-4">
                        <img id="discussion-avatar" class="pure-img" src="{{data.user_img}}" alt="Avatar">
                    </div>
                    <div class="pure-u-1-2">
                        <h4>Whats on your mind, {{session["user"]["userinfo"]["name"]}}?</h4>
                    </div>
                    <div class="pure-u-1-4">
                        <div id="makePost">
                            <a class="pure-button" id="create-discussion">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                        </div>
                    </div> 
                    <div class="pure-u-1">
                        <div id="postDicussionDiv">
                            <form id="discussionForm" class="pure-form" action="/community/discussion/create" method="post">
                                <fieldset>
                                    <div id="discussionTitle">
                                        <label for="stacked-title">Title: </label>
                                        <input type="text" name="title" id="stacked-title" placeholder="Title" required maxlength="64"/>
                                    </div>
                                    <div id="postFilter">
                                        <label for="stacked-cat">Posting in Forum: </label>
                                            <select name="category" id="stacked-category" required>
                                                <option value="">Select Category</option>
                                                {% for category in data.categories %}
                                                <option value={{category[0]}}>{{category[0]}}</option>
                                                {% endfor %}
                                            </select>
                                    </div>
                                    <div class="editor-container">
                                        <div id="editor">
                                        </div>
                                    </div>
                                    <input type="hidden" name="content" id="discussionData">
                                    <div id="cancelPost-container">
                                            <button id="cancel-post" type="button" class="pure-button">Cancel</button>
                                            <button class="pure-button pure-button-primary">Submit Post</button>
                                    </div>    
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div id="content-left-large">
                <h4>Please login to make a post</h4>
            </div>
        {% endif %}
        <div class="separator"></div>
        {% for recent_post in data.recent_posts %}
        <div id="content-left-large">
            <div id="post">
                <h2><a class="hidden-link-button" href="{{ url_for('create_post.detail', post_id=recent_post[8]) }}">{{recent_post[0]}}</a></h2>
                <div id="author">
                    <div class="pure-g">
                        <div class="pure-u-1-9">
                            <img id="avatar_img" class="pure-img" src="{{recent_post[6]}}" alt="Avatar">
            
                        </div>
                        <div class="pure-u-1-9">
                            <h4 id="author_name">{{recent_post[5]}}</h4>
                        </div>
                        <div class="pure-u-1-9">
                            <p id="post_date">• {{recent_post[3]}}</p>
                        </div>
                    </div>
                
                </div>
                <div class="post-content">
                    {{recent_post[1]|safe}} 
                    <!-- this feels very much not safe, can we trust the html in our database?? -->
                </div>
                
                <i id="like_button_{{recent_post[8]}}" class="like_button fa-regular fa-heart fa-lg"></i>
                <div class="button_like" data-id="{{recent_post[8]}}"></div>
                <a class="hidden-link-button" href="{{ url_for('create_post.detail', post_id=recent_post[8]) }}"><i id="comment_button" class="fa-regular fa-comment fa-lg"></i>&nbsp;&nbsp;&nbsp;{{recent_post[7]}}</a>
            </div>
        </div>
        <div class="separator"></div>
        {% endfor %}
        <div class="page-buttons">
        <h4>Page {{data.page + 1}}</h4>
        {% if data.page > 0 %}
        <a id="left-page-button" href="?page={{data.page-1}}"><i class="fa-solid fa-square-caret-left fa-lg"></i></a>
        {% else %}
        <a id="left-page-button"><i class="fa-regular fa-square-caret-left fa-lg"></i></a>
        {% endif %}

        {% if data.page < data.page_count-1 %}
        <a id = "right-page-button" href="?page={{data.page+1}}"><i class="fa-solid fa-square-caret-right fa-lg"></i></a>
        {% else %}
        <a id="right-page-button"><i class="fa-regular fa-square-caret-right fa-lg"></i></a>
        {% endif %}
        </div>
    </div>
    <div class="pure-u-1-4">
    <div class="separator"></div>
    <div id="content-right">
      <h2>Community Activity</h2>
      <div id="category-activity-div">
        <h4>Games</h4>
        <span><i class="fa-regular fa-comments"></i> {{data.games_category_count}} Posts • New Reply {{data.recent_games[3]}} ago</span>
        <h4>Character</h4>
        <span><i class="fa-regular fa-comments"></i> {{data.character_category_count}} Posts • New Reply {{data.recent_character[3]}} ago</span>
        <h4>Content</h4>
        <span><i class="fa-regular fa-comments"></i> {{data.content_category_count}} Posts • New Reply {{data.recent_content[3]}} ago</span>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/details.html
{% extends "base.html" %}

{% block css_links %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/details.css') }}">
{% endblock %}

{% block js_scripts %}
  <script src="{{ url_for('static', filename='js/details.js') }}"></script>
{% endblock %}

{% block title %}{{post_data.post_title}}{% endblock %}

{% block header %}
<h1>Post details</h1>
{% endblock %}

{% block content %}
<div class="pure-g">
  <div class="pure-u-1-5">
    <div id="content-left">
      <div class="blog">
        <div class="pic">
          <img src="{{ author_data.author_img }}" alt="User Image">
        </div>
        <div class="pure-g userinfo">
          <div class="username">{{ author_data.author_name }}</div>
          <div class="userpos">{{ author_data.author_post }} posts | {{author_data.author_fan}} followers</div>
          <div class="userbio">{{ author_data.author_bio| safe}}</div>
        </div>
    </div>
    </div>
  </div>

  <div class="pure-u-3-5">
    <div class="content-right-large activities postbar">
    <h2 class="post-title">{{ post_data.post_title }}</h2>
    <div class="post_container">
        <p class="author-time">Author: {{ author_data.author_name }}&nbsp;&nbsp;&nbsp;&nbsp; Created time：{{ post_data.post_time }}</p>
        <div id="inline_separator"></div>
        <p class="post_content">
            {{ post_data.post_content | safe}}
        </p>
      </div>
    <div id="post_separator"></div>
    {% if session.get("user") %}
      <div id="post_comment">
        <div style="margin-bottom: 4px">
          <span>Comment as {{user}}</span>
        </div>
        <form id="comment-form" class="pure-form" action="{{ url_for('create_post.detail', post_id=post_data.post_id) }}" method="post">
          <div id="editor-post">
          </div>
          <input type="hidden" name="content" id="postData">
          <div id="post-btn">
            <button class="pure-button">Post</button>
          </div>
        </form>
      </div>
    {% else %}
      <div id="msg">
        <span>Wanna leave a comment? Please sign in 😉</span>
      </div>
    {% endif %} 
    <div id="post_separator"></div>
    <div id="comment-header">
      <h4>Comments ({{ comments|length }})</h4>
    </div>
    <div id="post_separator"></div>
    {% for comment in comments %}
    <div id="post">
        <div id="post-author">
            <div class="pure-g">
                <div class="pure-u-1-9">
                    <img id="avatar_img" class="pure-img" src="{{comment[1][2]}}" alt="Avatar">
                </div>
                <div class="pure-u-1-9">
                    <h4 id="author_name">{{comment[1][1]}}</h4>
                </div>
                <div class="pure-u-1-9">
                    <p id="post_date">• {{comment[4]}}</p>
                </div>
            </div>
        </div>
        <div class="post-content">
            {{comment[3] |safe}} 
        </div>
    </div>  
    <div id="post_separator"></div>
    {% endfor %}
  </div>
  </div>

  <div class="pure-u-1-5">
    <div id="content-right">
      <div id="header">
        <div id="about">About category</div>
      </div>
      <div id="category" style="padding:12px">
        <div id="image_section">
          <img id="category_img" src="{{category_data.category_icon}}" alt="">
          <div>
            <a class="link-button" href="/categories/{{post_data.post_category}}">{{post_data.post_category}}</a>
          </div>
        </div>
      </div>
      <div>{{category_data.category_description}}</div>
      <div id="inline_separator"></div>
      <div id="create_post">
        <a class="pure-button" role="button" tabindex="0" href="/post/create">Create Post</a>
      </div>
    </div>
  </div>
</div>
<div class="separator"></div>


{% endblock %}

templates/home.html
{% extends "base_multibar.html" %}

{% block css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}

{% block js_scripts %}
    <script async defer src="{{ url_for('static', filename='js/home.js') }}"></script>
{% endblock %}

{% block title %}Home{% endblock %}

{% block main_content %}
{% for recent_post in data.recent_posts %}
{% set post_link = data.post_url + recent_post[2].lower() + "/?page=" + recent_post[0] %}
<div class="post ql-editor">

<h2 class="post_title"><a class=hidden-link-button href='{{post_link}}'>{{recent_post[0]}}</a></h2>
<!-- <h2 class="post_title"><a href="{{ url_for('create_post.detail', post_id=recent_post[8]) }}">{{recent_post[0]}}</a></h2> -->
    <div class="author">
        <div class="pure-g">
            <div class="pure-u-1-9">
                <img class="avatar_img pure-img" src="{{recent_post[6]}}" alt="Avatar">

            </div>
            <div class="pure-u-1-9">
                <h4 class="author_name">{{recent_post[5]}}</h4>
            </div>
            <div class="pure-u-1-9">
                <p class="post_date">• {{recent_post[3]}}</p>
            </div>
        </div>
    
    </div>
    <div class="post-content">
        {{recent_post[1]|safe}} 
        <!-- this feels very much not safe, can we trust the html in our database?? -->
    </div>
    
    <i id="like_button_{{recent_post[8]}}" class="like_button fa-regular fa-heart fa-lg"></i>
    <div class="button_like" data-id="{{recent_post[8]}}"></div>
    <div id="read-more-button">
        <a class=hidden-link-button href='{{post_link}}'><button class="pure-button">Read More</button></a>
    </div>
</div>
<div class="separator"></div>
{% endfor %}
<h4>Page {{data.page + 1}}</h4>
<div class="page-buttons">
{% if data.page > 0 %}
<a id="left-page-button" href="?page={{data.page-1}}"><i class="fa-solid fa-square-caret-left fa-lg"></i></a>
{% else %}
<a id="left-page-button"><i class="fa-regular fa-square-caret-left fa-lg"></i></a>
{% endif %}

{% if data.page < data.page_count-1 %}
<a id = "right-page-button" href="?page={{data.page+1}}"><i class="fa-solid fa-square-caret-right fa-lg"></i></a>
{% else %}
<a id="right-page-button"><i class="fa-regular fa-square-caret-right fa-lg"></i></a>
{% endif %}
</div>

{% endblock %}

{% block right_content %}
    <h2>Trending Tags</h2>
    {% for trending_tag in data.trending_tags %}
    <div class="trending-tag-section">
        <a href="/categories/{{trending_tag[2].lower()}}/{{trending_tag[0].lower()}}"><button class="pure-button"># {{trending_tag[0]}}</button></a> <p class="trending-tag-text"> {{trending_tag[1]}} posts <span class="trending-tag-cat">in {{trending_tag[2]}}<span></p>
    </div>
    {% endfor %}
{% endblock %}